---
title: "Palaeoclimatic constraints on the Great American Biotic Interchange"
author:  
  - Lucas Buffan¹, Adrián Castro Insua², Fabien L. Condamine¹, Sara Varela²
format:
  docx:
      number-sections: false
      reference-doc: template.docx
editor: visual
bibliography: references.bib
csl: biology-letters.csl
---

Affiliations:\
¹ Institut des Sciences de l’Evolution de Montpellier, Université de Montpellier, CNRS, IRD, Place Eugène Bataillon, 34095 Montpellier cedex 5, France.\
² Centro de Investigación Mariña, Departamento de Ecoloxía e Bioloxía Animal, Universidade de Vigo, Campus Lagoas-Marcosende, 36310 Vigo, Spain

# Potential journals

## Primary aim

Biology Letters

## Others that could fit

Proceedings B? Global ecology & Biogeography? Journal of Biogeography? Current Biology?

# Introduction

### Paragraph 1. Geodispersals + GABI broad description. Towards asymmetry

Throughout its evolutionary history, the biosphere has been repeatedly marked by the occurrence of geodispersal events, that is, exchanges of large species pools across landmasses [*e*.*g*., @couvreur2011]. When focusing on land mammals, a famous example of geodispersal is the late Cenozoic faunal exchange between the Americas, catalysed by the establishment of a physical connection between both continents (isthmus of Panama), termed Great American Biotic Interchange (GABI) [@marshall1982]. Though the exact timing of the closure of isthmus is still debated [@montes2015; @jaramillo2018; @odea2016], the fossil record and molecular phylogenies both agree with a late Miocene onset of land mammal exchange between the Americas, with most effective crossings occurring from *c.* 3.5 Ma onwards [@verzi2008; @bacon2015; @bacon2016]. Despite its textbook nature, a puzzling feature of the GABI is that it impacted both continent's mammalian faunas very differently. In fact, evidence from the fossil record indicates that the early phases of the GABI were marked by reciprocal mammal exchanges between the Americas, but that the Pleistocene times witnessed an increasing proportion of North American mammals establishing southwards [@webb1976; @marshall1982]. At present, only around 10% of the land mammal genera inhabiting North and Central America have a South American ancestry (number reduced to two single species when considering North America above Mexico), whereas it is estimated that half of living South American mammal genera descend from a North American lineage [@marshall1988]. Therefore, this intercontinental faunal exchange has been highly asymmetric.

### Paragraph 2. Asymmetry: Drivers? History and state-of-the-art

Higher extinction rates of endemic South American taxa in South America during the Pliocene were suggested as the prevailing mechanism explaining this asymmetry [@carrillo2020]. However, the drivers behind this macroevolutionary imbalance, going against MacArthur & Wilson's equilibrium theory [@macarthur1967], remain unresolved. Many hypotheses have been proposed to this end. The question has been primarily viewed through the lens of biotic interactions, being either competition between clades assumed to have similar ecologies [@webb1976; @simpson1980; @domingo2020; but see @prevosti2013; @tarquini2022; @marsà2025] or predation of predator-naive preys [@webb1976; @marshall1990; @faurby2016]. Other studies proposed the implication of abiotic factors. Some put the emphasis on Pleistocene climate fluctuations and the consequent alternating phases of emergence of landscape opening across Central America, in turn favouring the dispersal of large temperate-adapted mammals to the detriment of tropical-adapted ones [@marshall1990; @webb1991; @bacon2016]. Others drew direct relationships between the higher extinction rates of native South American mammal genera and temperature change [@freitas-oliveira2024]. However, our understanding of the underlying forces that drove the GABI's asymmetry has been limited to statistical analyses primarily relying on fossil data, naturally biased and incomplete [@krone2024].

### Paragraph 3. Mechanistic eco-evo modelling

Recent improvements in process-explicit modelling have marked a turning point in the study of biodiversity patterns from a causal perspective [@pilowsky2022]. In particular, mechanistic eco-evolutionary models ... [@hagen2021]

Possibility to run computer experiments and draw casual links between biodiversity patterns and (a)biotic factors Proved efficient in a wide range of questions.

Here, using a mechanistic biodiversity simulator, we explore the extent to which palaeoclimate dynamics throughout the last 5 My can explain the observed asymmetry in the land mammal exchange that occurred across the Americas.

# Materials and methods

What we want to compare:

-   Proportion of successful exchanges when starting from North v.s. South\
-   Is there any change in diversification rates after crossing Panama's isthmus? Do crossers from the North experience enhanced diversification than in the other way round?

Here, we term "North America" North + Central America

## Palaeoclimate data

We used the spatio-temporal terrestrial palaeoclimate series from the PALEO-PGEM atmosphere-ocean general circulation model [@holden2019], covering the last 5 Myrs with a 1 \times 1 ° spatial resolution [@barreto2023]. For the scope of this work, we used two bioclimatic variables: mean annual temperature (MAT, BIO1) and mean annual precipitation (MAP, BIO12).

We further reclassified these monthly palaeoclimate layers across the last five million years according to Köppen-Geiger broad climate types [@galván2023]. This classification divides the world into five broad climatic regions: Polar, Cold, Temperate, Arid and Tropical.

## Simulation model and modelling schemes

We performed our spatially-explicit simulations of biodiversity using the General Engine for Eco-Evolutionary SImulationS, *gen3sis*, v1.5.11 [@hagen2021]. Simulations, moving forward-in-time with a 10ky time step, tracked the dispersion and diversification of ancestral lineages either originating in North, South America or both, throughout the last 5 Myr.

The ancestral range of a starting lineage was randomly selected within the desired ancestral area (*i*.*e*., North, South America or both). To avoid oversampling high latitudes, we merged the ancestral landscape with the centroids of an equal-area grid (\~100km spacing) generated using the R package *h3jsr* [@obrien2023]. We then sampled a centroid at random and retrieved the corresponding cell in our landscape.

Importantly, since the palaeoclimate reconstructions that we used ignored tectonic plate motion − a fairly reasonable assumption for a 5-Myr time frame − continental position in our landscapes was held constant across simulations. Therefore, in this framework, changes in connectivity between North and South America could only arise from the environment.

Spatial threshold between North and South America: middle of Panamá.

Divergence threshold vs. divergence factor.

# Results

# Discussion

Smoothing asymmetry =\> echo to birds [@weir2009], flying behaviour relaxing constraints applied to land mammals ?

Species pool proved relevant in the case of the interchange along the Wallacea [@skeels2023]. But here, we expect to find more species in South America, encompassing one of earth's major and long-standing biodiversity hotspot -- Amazonia [@antonelli2018] -- than in North America.

Competition involving clades of similar ecology appeared as a likely first-order explanation to the recent demise of South American endemic mammal clades such as native ungulates [@croft2020] or sparassodonts (metatherian predators, [@pino2022; @tarquini2022]) that followed the establishment of northern lineages [@simpson1980]. This hypothesis mostly relied on striking morphological convergences between the clades assumed to have competed (*e*.*g*., sabertooth among predators, high-crowned and ever-growing cheek teeth among herbivores). However, several analyses of the fossil record provided no evidence for competition between native South American mammals and their northern counterparts [@prevosti2013; @tarquini2022]. That being said, using phylogenetic regressions, Faurby et al. [@faurby2016] found support for another biotic interaction as a likely driver behind GABI's asymmetry: predation. They indeed characterised a higher prevalence of traits increasing prey susceptibility among the endemic south american mammals. + larger niches of competitors [@domingo2020]

\newpage

# References

::: {#refs}
:::
