---
title: "Palaeoclimatic constraints behind the Great American Biotic Interchange: insights from eco-evolutionary simulations"
author:  
  - Lucas Buffan¹, Adrián Castro Insua², Fabien L. Condamine¹, Sara Varela²
format:
  docx:
      number-sections: false
      reference-doc: template.docx
editor: visual
bibliography: references.bib
csl: biology-letters.csl
---

Affiliations:\
¹ Institut des Sciences de l’Evolution de Montpellier, Université de Montpellier, CNRS, IRD, Place Eugène Bataillon, 34095 Montpellier cedex 5, France.\
² Centro de Investigación Mariña, Departamento de Ecoloxía e Bioloxía Animal, Universidade de Vigo, Campus Lagoas-Marcosende, 36310 Vigo, Spain

# Potential journals

## Primary aim

Biology Letters

## Others that could fit

Proceedings B? Global ecology & Biogeography? Journal of Biogeography? Current Biology?

# Introduction

### Paragraph 1. Geodispersals + GABI broad description. Towards asymmetry

The Great American Biotic Interchange (GABI) characterises the recent large-scale faunal exchange -- mostly regarding land mammals -- that occurred between the Americas, favoured by the establishment of the isthmus of Panama [@marshall1982]. Though the exact timing of the closure of the isthmus is still debated [@montes2015; @jaramillo2018; @odea2016], the fossil record and molecular phylogenies both agree with a late Miocene onset of land mammal exchange between the Americas, with most effective crossings occurring from *c.* 3.5 Ma onwards [@verzi2008; @woodburne2010; @bacon2015; @bacon2016]. Despite its textbook nature, a puzzling feature of the GABI is that it impacted both continent's mammalian faunas very differently. In fact, evidence from the fossil record indicates that the early phases of the GABI were marked by reciprocal exchanges between the Americas [@webb1976; @marshall1982]. However, during the Quaternary, the ability of migrant lineages to maintain in the foreign area became greater in South America, and many native South American mammal lineages concomitantly declined, some of which even going totally extinct [@webb1991; @cione2015]. Hence, it turns out that this intercontinental faunal exchange has been strikingly asymmetric.

### Paragraph 2. Asymmetry: Drivers? History and state-of-the-art

Although this macroecological imbalance is unquestionable, so far, no clear consensus regarding the forces underlying this asymmetry has been established. On one hand, biotic interactions, involving migrant and native species, have often been proposed to this aim. These would mostly include competition [@webb1976; @simpson1980; @domingo2020] and predation of predator-naive preys [@webb1976; @marshall1990; @faurby2016; @fernández-monescillo2025]. However, their contribution to the asymmetry of the GABI has been increasingly called into question [*e*.*g*., @prevosti2013; @tarquini2022; @marsà2025]. On the other hand, many studies illustrated the ability of abiotic factors -- *i*.*e*., related to species' physical environment, such as climate change -- to have a large-scale impact on biodiversity patterns over macroevolutionary timescales [*e*.*g*., @blois2009; @condamine2013; @kiessling2025]. In the case of the GABI, several studies proposed that palaeoclimate change shaped unequal dispersal abilities between northern and southern taxa [@marshall1990; @webb1991; @bacon2016; @freitas-oliveira2024], although the hypothesis according to which the asymmetry of the GABI would stem from dispersal rates is still largely debated [*e*.*g*., @carrillo2020].


but, so far, the only studies exploring this issue relied on correlative approaches making use of fossil data, and there is a lack of framework tackling the issue from a mechanistic perspective.


Other studies proposed the implication of abiotic factors. Some put the emphasis on Pleistocene climate fluctuations and the consequent alternating phases of emergence of landscape opening across Central America, in turn favouring the dispersal of large temperate-adapted mammals to the detriment of tropical-adapted ones [@marshall1990; @webb1991; @bacon2016]. Others drew direct relationships between the higher extinction rates of native South American mammal genera and temperature change [@freitas-oliveira2024].

However, so far, such studies have been limited to statistical analyses primarily relying on fossil data, naturally biased and incomplete [@krone2024], and there is a lack of studies tackling the issue from a mechanistic perspective.

### Paragraph 3. Mechanistic eco-evo modelling

Recent improvements in process-explicit modelling have marked a turning point in the study of biodiversity patterns from a causal perspective [@pilowsky2022]. In particular, mechanistic eco-evolutionary models ... [@hagen2021]

Possibility to run computer experiments and draw causal links between biodiversity patterns and (a)biotic factors Proved efficient in a wide range of questions.

Here, using a mechanistic biodiversity simulator, we explore the extent to which palaeoclimate dynamics throughout the last 5 My can explain the observed asymmetry in the land mammal exchange that occurred across the Americas. We simulated a diversifying clade in a landscape made up with two palaeoclimate components starting from a single ancestor either in North or in South America, we hypothesise that (i) simulations starting from a North American ancestor would result in a higher success at reaching the other continent than the other way round, (ii) (iii)

# Materials and methods

What we want to compare:

-   Proportion of successful exchanges when starting from North v.s. South\
-   Is there any change in diversification rates after crossing Panama's isthmus? Do crossers from the North experience enhanced diversification than in the other way round?

Here, we term "North America" North + Central America

Quantify:\
- Distrib° of occupied area\
- Diversity (nb of species) in the colonised area\
- (?)Reachability: how long does it take to reach the other area? (surely related to distance to exchange point)

## Palaeoclimate data

We used the spatio-temporal terrestrial palaeoclimate series from the PALEO-PGEM atmosphere-ocean general circulation model [@holden2019], covering the last 5 Myrs with a 1 \times 1 ° spatial resolution [@barreto2023]. For the scope of this work, we used two bioclimatic variables: mean annual temperature (MAT, BIO1) and mean annual precipitation (MAP, BIO12).

We further reclassified these monthly palaeoclimate layers across the last five million years according to Köppen-Geiger broad climate types [@galván2023]. This classification divides the world into five broad climatic regions: Polar, Cold, Temperate, Arid and Tropical.

## Simulation model and modelling schemes

We performed our spatially-explicit simulations of biodiversity using the General Engine for Eco-Evolutionary SImulationS, *gen3sis*, v1.5.11 [@hagen2021]. Simulations, moving forward-in-time with a 10ky time step, tracked the dispersion and diversification of ancestral lineages either originating in North, South America or both, throughout the last 5 Myr.

The ancestral range of a starting lineage was randomly selected within the desired ancestral area (*i*.*e*., North, South America or both). To avoid oversampling high latitudes, we merged the ancestral landscape with the centroids of an equal-area grid (\~100km spacing) generated using the R package *h3jsr* [@obrien2023]. We then sampled a centroid at random and retrieved the corresponding cell in our landscape.

Importantly, since the palaeoclimate reconstructions that we used ignored tectonic plate motion − a fairly reasonable assumption for a 5-Myr time frame − continental position in our landscapes was held constant across simulations. Therefore, in this framework, changes in connectivity between North and South America could only arise from the environment.

Spatial threshold between North and South America: middle of Panamá.

Divergence threshold vs. divergence factor.

# Results

# Discussion

Smoothing asymmetry =\> echo to birds [@weir2009], flying behaviour relaxing constraints applied to land mammals ?

Species pool proved relevant in the case of the interchange along the Wallacea [@skeels2023]. But here, we expect to find more species in South America, encompassing one of earth's major and long-standing biodiversity hotspot -- Amazonia [@antonelli2018] -- than in North America.

Is it just about **reaching** or more about **reaching & surviving**?

several studies proposed that palaeoclimate change shaped unequal dispersal abilities between northern and southern taxa [@marshall1990; @webb1991; @bacon2016; @freitas-oliveira2024], although the hypothesis according to which the asymmetry of the GABI would stem from dispersal rates is still largely debated [*e*.*g*., @carrillo2020].

## Limitations & perspectives

Maybe one of the most obvious caveats of our study stems from the assumption of fixed palaeogeography, particularly near the isthmus, wheras we know that this region changed across our study.

# Thrash

Throughout its evolutionary history, the biosphere has been repeatedly marked by the occurrence of geodispersal events, that is, exchanges of large species pools across landmasses [*e*.*g*., @couvreur2011, @upchurch2024].

Competition involving clades of similar ecology appeared as a likely first-order explanation to the recent demise of South American endemic mammal clades such as native ungulates [@croft2020] or sparassodonts (metatherian predators, [@pino2022; @tarquini2022]) that followed the establishment of northern lineages [@simpson1980]. This hypothesis mostly relied on striking morphological convergences between the clades assumed to have competed (*e*.*g*., sabertooth among predators, high-crowned and ever-growing cheek teeth among herbivores). However, several analyses of the fossil record provided no evidence for competition between native South American mammals and their northern counterparts [@prevosti2013; @tarquini2022]. That being said, using phylogenetic regressions, Faurby et al. [@faurby2016] found support for another biotic interaction as a likely driver behind GABI's asymmetry: predation. They indeed characterised a higher prevalence of traits increasing prey susceptibility among the endemic south american mammals. + larger niches of competitors [@domingo2020]

These would include Pleistocene climate fluctuations and the consequent alternating phases of emergence of open landscapes across Central America, in turn favouring the dispersal of large temperate-adapted mammals to the detriment of tropical-adapted ones

\newpage

# References

::: {#refs}
:::
