---
title: "Palaeoclimatic constraints behind the Great American Biotic Interchange: insights from eco-evolutionary simulations"
author:  
  - Lucas Buffan¹, Adrián Castro Insua², Fabien L. Condamine¹, Sara Varela²
format:
  docx:
      number-sections: false
      reference-doc: template.docx
editor: visual
bibliography: references.bib
csl: biology-letters.csl
---

Affiliations:\
¹ Institut des Sciences de l’Evolution de Montpellier, Université de Montpellier, CNRS, IRD, Place Eugène Bataillon, 34095 Montpellier cedex 5, France.\
² Centro de Investigación Mariña, Departamento de Ecoloxía e Bioloxía Animal, Universidade de Vigo, Campus Lagoas-Marcosende, 36310 Vigo, Spain

# Potential journals

## Primary aim

Biology Letters

## Others that could fit

Proceedings B? Global ecology & Biogeography? Journal of Biogeography? Current Biology?

# Introduction

### Paragraph 1. Geodispersals + GABI broad description. Towards asymmetry

The Great American Biotic Interchange (GABI) refers to the large-scale faunal exchange -- mostly affecting land mammals -- that occurred between the Americas, favoured by the establishment of the isthmus of Panama [@marshall1982]. Though the exact timing of the closure of the isthmus is still debated [@montes2015; @jaramillo2018; @odea2016], palaeontological evidence and molecular phylogenies both agree with a late Miocene onset of land mammal exchange between the Americas, with most effective crossings occurring from *c.* 3.5 Ma onwards [@verzi2008; @woodburne2010; @bacon2015; @bacon2016]. Despite its textbook nature, a puzzling feature of the GABI is that it impacted both continent's mammalian faunas very differently. In fact, evidence from the fossil record indicates that the early phases of the GABI were marked by reciprocal exchanges between the Americas [@webb1976; @marshall1982]. However, during the Quaternary, the ability of migrant lineages to maintain in the foreign area became greater in South America, and many native South American mammal lineages concomitantly declined, some of which even going totally extinct [@webb1991; @cione2015]. Hence, it turns out that this intercontinental faunal exchange has been strikingly asymmetric.

### Paragraph 2. Asymmetry: Drivers? History and state-of-the-art

Although this macroecological imbalance is unquestionable, so far, no clear consensus regarding the forces underlying this asymmetry has been established. On one hand, biotic interactions involving migrant and native species have often been proposed to this aim. These would include competition [@webb1976; @simpson1980; @domingo2020] or predation of predator-naive preys [@webb1976; @marshall1990; @faurby2016; @fernández-monescillo2025]. However, their contribution to the asymmetry of the GABI has been increasingly called into question [*e*.*g*., @prevosti2013; @tarquini2022; @marsà2025]. On the other hand, many studies illustrated the ability of abiotic factors -- *i*.*e*., related to species' physical environment, such as climate -- to have a large-scale impact on biodiversity patterns at different timescales [*e*.*g*., @blois2009; @condamine2013; @nogués-bravo2018; @kiessling2025]. In the case of the GABI, several works proposed or found support for a contribution of palaeoclimate change (mostly during the Pleistocene) in the asymmetry of this widely-known exchange [*e*.*g*., @marshall1990; @webb1991; @bacon2016; @freitas-oliveira2024]. However, so far, such studies have been limited to statistical analyses primarily relying on fossil data, naturally biased and incomplete [@krone2024], and there is a lack of studies tackling the issue from a mechanistic perspective.

### Paragraph 3. Mechanistic eco-evo modelling and aim of the study

Recent improvements in process-explicit modelling have marked a turning point in the study of biodiversity [@pilowsky2022]. By combining a landscape made up with palaeoclimatic variables and a set of eco-evolutionary rules according to which virtual species are simulated, mechanistic eco-evolutionary models offer the unique opportunity to casually explore the way biodiversity patterns arise and are maintained through evolutionary times [@hagen2023]. Recently, this family of models has provided unprecedented insights into the underlying forces behind widely-recognised biodiversity patterns, such as the latitudinal biodiversity gradient [@hagen2021], the diversity desequilibrium between tropical rainforests across the globe [reload ref], the build-up of the unique biodiversity along the Wallace line [skeels2023 wallacea] and many others [*e*.*g*., @boschman2023; @skeels2023; liu2024]. Here, we use a mechanistic biodiversity simulator to explore the extent to which palaeoclimate dynamics throughout the last 5 My can explain the observed asymmetry in the land mammal exchange that occurred across the Americas. We simulated a diversifying clade in a landscape made up with two palaeoclimate variables (annual temperature and precipitations) starting from a single ancestor, either in North or South America. We hypothesise that (i) simulations starting from a North American ancestor would be more successful at reaching the other continent than the other way round, (ii) successful simulations starting from a North American ancestor would result in a more diverse and spatially spread radiation in the foreign continents and (iii) part of this asymmetry stems from the unequal biome areas between North and South America.

# Materials and methods

Here, we term "North America" North + Central America. The delimitation between both continents was arbitrarily set in the middle of Panama (coordinates).

Quantify:\
- Distrib° of occupied area\
- Diversity (nb of species) in the colonised area\
- (?)Reachability: how long does it take to reach the other area? (surely related to distance to exchange point)

## Palaeoclimate data

We used the spatio-temporal terrestrial palaeoclimate series from the PALEO-PGEM atmosphere-ocean general circulation model [@holden2019], covering the last 5 Myrs with a 1 \times 1 ° spatial resolution [@barreto2023]. For the scope of this work, we used two bioclimatic variables: mean annual temperature (MAT, BIO1) and mean annual precipitation (MAP, BIO12).

We further reclassified these monthly palaeoclimate layers across the last five million years according to Köppen-Geiger broad climate types [@galván2023]. This classification divides the world into five broad climatic regions: Polar, Cold, Temperate, Arid and Tropical.

## Simulation model and modelling schemes

We performed our spatially-explicit simulations of biodiversity using the General Engine for Eco-Evolutionary SImulationS, gen3sis, v1.5.11 [@hagen2021]. Simulations, moving forward-in-time with a 10ky time step, tracked the followed of a clade arising from a single ancestral population, either originating in North or in South America, throughout the last 5 Myr. In gen3sis, virtual species evolve following a set of four rules: dispersal, speciation, environmental filtering and trait evolution. All simulation scenarios that we implemented only differed on the last rule (trait evolution), the first three being common to all models (or at least partly).

Within the gridded landscape, a population inhabiting a cell could disperse to the surrounding cells with an intensity sampled in a Weibull distribution (shape and scale parameters available in SI). If, by chance, populations making up a species happened to be disconnected, they would accumulate divergence across the time steps as long as they get disconnected at a rate ruled by a divergence factor, here set to $0.05$. This value, around an order of magnitude higher than those usually encoutered in gen3sis case studies [*e*.*g*., @hagen2021; @boschman2023; skeels 2023] was chosen in the reason of our high number of time steps ($500$). Once passed a divergence threshold (varying across replicates, see SI), speciation occurred.

As our goal was to evaluate the extent to which palaeoclimate change may have shaped the unequal success of North American taxa establishing southwards compared to South American taxa establishing northwards, local climate was set as the only constraint for a population to maintain in a given cell. Each species was therefore assigned a two-dimensional climatic niche, one axis corresponding to temperature suitability and the other to precipitation suitability. The abundance of a species along an environmental gradient was ruled by two parameters -- that we also call traits --, an optimum and a breadth. A population could maintain in a given cell only if the difference between its optima and local climate (both temperature and precipitation) was below its breadth (or tolerance) parameters.

Across our simulation scenarios, we modulated the ability of species to cope with climate change. In the full-adaptationist model (M1), climatic optima were able to evolve in the direction of local climate change. Evolution was operated It is important to notice that niche parameters were population (and not species) specific. In the zero-adaptationist model (M0), niche optima couldn't evolve and were therefore held constant (to the initial value) across all simulations. 

The range of the ancestor was randomly selected within the desired ancestral area (*i*.*e*., North or South America). To avoid oversampling high latitudes, we merged the ancestral landscape with the centroids of an equal-area grid (\~100km spacing) generated using the R package *h3jsr* [@obrien2023]. We then sampled a centroid at random and retrieved the corresponding cell in our landscape. To reduce the probability of initial crash, the temperature and/or precipitation optima parameter of the ancestor were set to those of the local environment. 

Importantly, since the palaeoclimate reconstructions that we used ignored tectonic plate motion − a reasonable assumption for a 5-Myr time frame − continental position in our landscapes was held constant across simulations. Therefore, in this framework, changes in connectivity between North and South America could only arise from the environment.

Sobol' sequences for parameter space exploration, as done by skeels & co.

Divergence threshold vs. divergence factor.

A total of 500 replicates was made under each scenario, both with North and South America as an ancestral area. 

## Postprocessing and quantifications

blabla

# Results

# Discussion

Smoothing asymmetry =\> echo to birds [@weir2009], flying behaviour relaxing constraints applied to land mammals ?

Species pool proved relevant in the case of the interchange along the Wallacea [@skeels2023]. But here, we expect to find more species in South America, encompassing one of earth's major and long-standing biodiversity hotspot -- Amazonia [@antonelli2018] -- than in North America.

Is it just about **reaching** or more about **reaching & surviving**?

Other studies proposed the implication of abiotic factors. Some put the emphasis on Pleistocene climate fluctuations and the consequent alternating phases of emergence of landscape opening across Central America, in turn favouring the dispersal of large temperate-adapted mammals to the detriment of tropical-adapted ones [@marshall1990; @webb1991; @bacon2016]. Others drew direct relationships between the higher extinction rates of native South American mammal genera and temperature change [@freitas-oliveira2024].

several studies proposed that palaeoclimate change shaped unequal dispersal abilities between northern and southern taxa [@marshall1990; @webb1991; @bacon2016; @freitas-oliveira2024], although the hypothesis according to which the asymmetry of the GABI would stem from dispersal rates is still largely debated [*e*.*g*., @carrillo2020].

## Limitations & perspectives

Maybe one of the most obvious caveats of our study stems from the assumption of fixed palaeogeography, particularly near the isthmus, wheras we know that this region changed across our study.

# Thrash

Throughout its evolutionary history, the biosphere has been repeatedly marked by the occurrence of geodispersal events, that is, exchanges of large species pools across landmasses [*e*.*g*., @couvreur2011, @upchurch2024].

Competition involving clades of similar ecology appeared as a likely first-order explanation to the recent demise of South American endemic mammal clades such as native ungulates [@croft2020] or sparassodonts (metatherian predators, [@pino2022; @tarquini2022]) that followed the establishment of northern lineages [@simpson1980]. This hypothesis mostly relied on striking morphological convergences between the clades assumed to have competed (*e*.*g*., sabertooth among predators, high-crowned and ever-growing cheek teeth among herbivores). However, several analyses of the fossil record provided no evidence for competition between native South American mammals and their northern counterparts [@prevosti2013; @tarquini2022]. That being said, using phylogenetic regressions, Faurby et al. [@faurby2016] found support for another biotic interaction as a likely driver behind GABI's asymmetry: predation. They indeed characterised a higher prevalence of traits increasing prey susceptibility among the endemic south american mammals. + larger niches of competitors [@domingo2020]

These would include Pleistocene climate fluctuations and the consequent alternating phases of emergence of open landscapes across Central America, in turn favouring the dispersal of large temperate-adapted mammals to the detriment of tropical-adapted ones

\newpage

# References

::: {#refs}
:::
